sudo: false
language: python
services:
  - postgresql
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip/wheels
    - $HOME/virtualenv
env:
  - DJANGO_VERSION=2.1.4
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
before_script:
  - createuser -U postgres -d subtitlestatus
script:
  - python manage.py test
