# Generated by Django 2.2.17 on 2021-01-23 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import www.models


class Migration(migrations.Migration):

    replaces = [('www', '0001_initial'), ('www', '0002_subtitle_comment'), ('www', '0003_auto_20141207_0204'), ('www', '0004_auto_20141207_0207'), ('www', '0005_auto_20141207_0235'), ('www', '0006_auto_20141207_1534'), ('www', '0007_auto_20141207_1535'), ('www', '0008_auto_20141207_2058'), ('www', '0009_auto_20141208_0341'), ('www', '0010_auto_20141208_0342'), ('www', '0011_auto_20141208_0343'), ('www', '0012_auto_20141208_0348'), ('www', '0013_auto_20141208_0351'), ('www', '0014_auto_20141208_0411'), ('www', '0015_auto_20141208_0412'), ('www', '0016_auto_20141208_0416'), ('www', '0017_auto_20141210_0344'), ('www', '0018_auto_20141210_0415'), ('www', '0019_convert_talk_orig_language_to_language_id'), ('www', '0020_convert_subtitle_language_to_language_id'), ('www', '0029_remove_language_amara_order'), ('www', '0030_language_amara_order'), ('www', '0031_auto_20141210_0615'), ('www', '0032_auto_20141210_0621'), ('www', '0033_delete_language'), ('www', '0034_auto_20141210_0624'), ('www', '0035_auto_20141210_0625'), ('www', '0036_auto_20141210_0756'), ('www', '0037_auto_20141210_0800'), ('www', '0038_auto_20141210_0812'), ('www', '0039_auto_20141210_0814'), ('www', '0040_auto_20141210_0843'), ('www', '0041_auto_20141210_0843'), ('www', '0042_auto_20141210_0844'), ('www', '0043_auto_20141210_0844'), ('www', '0044_auto_20141210_0845'), ('www', '0045_auto_20141210_0845'), ('www', '0046_auto_20141210_0846'), ('www', '0047_auto_20141210_0922'), ('www', '0048_auto_20141210_0926'), ('www', '0049_auto_20141210_0926'), ('www', '0050_auto_20141210_0927'), ('www', '0051_auto_20141210_0954'), ('www', '0052_auto_20141210_1025'), ('www', '0053_auto_20141210_1033'), ('www', '0054_auto_20141210_1034'), ('www', '0055_auto_20141214_0528'), ('www', '0056_auto_20141214_0750'), ('www', '0057_auto_20141214_0751'), ('www', '0058_auto_20141214_0756'), ('www', '0059_auto_20141215_2340'), ('www', '0060_auto_20141216_1400'), ('www', '0061_auto_20141216_1406'), ('www', '0062_auto_20141216_1409'), ('www', '0063_subtitle_time_quality_check_done'), ('www', '0064_auto_20141222_1818'), ('www', '0065_subtitle_blocked'), ('www', '0066_auto_20150118_1719'), ('www', '0067_auto_20150125_2224'), ('www', '0068_auto_20150125_2227'), ('www', '0069_auto_20150126_0040'), ('www', '0070_auto_20150126_0159'), ('www', '0071_auto_20150126_0208'), ('www', '0072_auto_20150126_0209'), ('www', '0073_auto_20151211_0135'), ('www', '0074_auto_20151211_0136'), ('www', '0075_auto_20151211_0137'), ('www', '0076_auto_20151211_0137'), ('www', '0077_auto_20151211_0145'), ('www', '0078_subtitle_tweet'), ('www', '0079_event_hashtag'), ('www', '0080_auto_20160109_0222'), ('www', '0081_subtitle_tweet_autosync_done'), ('www', '0082_subtitle_last_changed_on_amara'), ('www', '0083_talk_guid'), ('www', '0084_language_lang_code_media'), ('www', '0085_auto_20160510_1834'), ('www', '0086_talk_file_name'), ('www', '0087_auto_20160512_1845'), ('www', '0088_event_subfolder_to_find_the_filenames'), ('www', '0089_speaker_doppelgaenger_of'), ('www', '0090_speaker_doppelgaenger_of'), ('www', '0091_speaker_doppelgaenger_of'), ('www', '0092_statistics'), ('www', '0093_auto_20160622_2338'), ('www', '0094_auto_20160623_0045'), ('www', '0095_remove_statistics_time_delta'), ('www', '0096_statistics_time_delta'), ('www', '0097_auto_20160626_1613'), ('www', '0098_statistics'), ('www', '0099_auto_20160626_2100'), ('www', '0100_auto_20161009_1253'), ('www', '0101_auto_20161009_1255'), ('www', '0102_auto_20161009_1307'), ('www', '0103_auto_20161009_1317'), ('www', '0104_auto_20161009_1321'), ('www', '0105_statistics_event_statistics_speaker'), ('www', '0107_auto_20161009_1407'), ('www', '0112_auto_20161009_1725'), ('www', '0113_auto_20161009_1728'), ('www', '0114_auto_20161009_2202'), ('www', '0115_auto_20161017_0027'), ('www', '0116_auto_20161017_0045'), ('www', '0117_auto_20161019_2015'), ('www', '0118_speaker_links'), ('www', '0119_auto_20161019_2033'), ('www', '0120_auto_20161019_2037'), ('www', '0121_subtitle_yt_caption_id'), ('www', '0122_event_blacklisted'), ('www', '0123_event_cdn_subtitles_root_folder'), ('www', '0124_subtitle_blacklisted'), ('www', '0125_event_subfolder_in_sync_folder'), ('www', '0126_auto_20171015_1701'), ('www', '0127_auto_20180122_1723'), ('www', '0128_transcript'), ('www', '0129_talk_transcript_by'), ('www', '0130_auto_20180128_0926'), ('www', '0131_auto_20180128_0929'), ('www', '0132_remove_talk_transcript_from_trint'), ('www', '0133_auto_20180128_2152'), ('www', '0134_auto_20180510_1419'), ('www', '0135_auto_20190106_1337'), ('www', '0136_auto_20190106_1917'), ('www', '0137_auto_20190106_1920'), ('www', '0138_auto_20190106_1929'), ('www', '0140_auto_20191222_1500'), ('www', '0141_auto_20191222_1507'), ('www', '0144_talk_c3subtitles_youtube_key'), ('www', '0145_talk_internal_comment'), ('www', '0146_remove_event_ftp_startfolder'), ('www', '0147_remove_event_cdn_subtitles_root_folder'), ('www', '0148_auto_20200102_1749'), ('www', '0149_remove_talk_link_to_logo'), ('www', '0150_auto_20200102_1759'), ('www', '0151_auto_20200102_1821'), ('www', '0152_remove_subtitle_yt_caption_id'), ('www', '0153_auto_20200102_1837'), ('www', '0154_auto_20200103_1730'), ('www', '0155_auto_20200103_2047'), ('www', '0156_add_kanboard_fields'), ('www', '0157_add_kanboard_check_constraints'), ('www', '0158_auto_20201225_1541'), ('www', '0159_auto_20201231_1821'), ('www', '0160_auto_20210101_1356'), ('www', '0161_auto_20210101_1402'), ('www', '0162_auto_20210101_1558'), ('www', '0163_auto_20210101_1600'), ('www', '0164_auto_20210108_1833'), ('www', '0165_remove_talk_youtube_key'), ('www', '0166_auto_20210108_1944'), ('www', '0167_auto_20210109_1144'), ('www', '0168_auto_20210109_1431'), ('www', '0169_auto_20210110_0240'), ('www', '0170_auto_20210123_1957')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('schedule_version', models.CharField(default='0.0', max_length=50)),
                ('acronym', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='No title yet', max_length=100)),
                ('start', models.DateField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('end', models.DateField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('timeslot_duration', models.TimeField(default='00:15')),
                ('days', models.PositiveSmallIntegerField(default=1)),
                ('schedule_xml_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('day_start', models.DateTimeField()),
                ('day_end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('language_en', models.CharField(default='', max_length=40)),
                ('language_de', models.CharField(default='', max_length=40)),
                ('lang_short_2', models.CharField(default='', max_length=3, unique=True)),
                ('lang_amara_short', models.CharField(default='', max_length=15, unique=True)),
                ('lang_short_srt', models.CharField(default='', max_length=15)),
                ('language_native', models.CharField(default='', max_length=40)),
                ('amara_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(default='kein Raum', max_length=30)),
                ('building', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('frab_id', models.PositiveSmallIntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('state_de', models.CharField(max_length=100)),
                ('state_en', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('track', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('frab_id_talk', models.PositiveSmallIntegerField(default=-1)),
                ('blacklisted', models.BooleanField(default=False)),
                ('link_to_logo', models.URLField(default='')),
                ('date', models.DateTimeField()),
                ('start', models.TimeField()),
                ('duration', models.TimeField()),
                ('title', models.CharField(default='ohne Titel', max_length=50)),
                ('subtitle_talk', models.CharField(default=' ', max_length=100)),
                ('abstract', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('pad_id', models.CharField(default='', max_length=30)),
                ('link_to_writable_pad', models.URLField(default='')),
                ('link_to_readable_pad', models.URLField(default='')),
                ('link_to_video_file', models.URLField(default='')),
                ('amara_key', models.CharField(default='', max_length=20)),
                ('youtube_key', models.CharField(max_length=20)),
                ('video_duration', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Event_Days')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Event')),
                ('orig_language', models.CharField(default='', max_length=11)),
                ('persons', models.ManyToManyField(default=None, to='www.Speaker')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Rooms')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Tracks')),
                ('type_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Type_of')),
                ('slug', models.SlugField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('talk_link_url', models.URLField()),
                ('talk_link_title', models.CharField(default='Link title', max_length=50)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Talk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('is_original_lang', models.BooleanField(default=False)),
                ('revision', models.PositiveSmallIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('time_processed_transcribing', models.TimeField(default='00:00')),
                ('time_processed_syncing', models.TimeField(default='00:00')),
                ('time_processed_translating', models.TimeField(default='00:00')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Language', to_field='lang_amara_short')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.States')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Talk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            sql=['UPDATE www_talk AS t SET orig_language = l.id FROM www_language AS l WHERE t.orig_language = l.lang_short_2;', 'ALTER TABLE www_talk ALTER COLUMN orig_language TYPE integer USING orig_language::integer;'],
            reverse_sql=['ALTER TABLE www_talk ALTER COLUMN orig_language TYPE character varying(11) USING orig_language::character varying(11);', 'UPDATE www_talk AS t SET orig_language = l.lang_short_2 FROM www_language AS l WHERE t.orig_language::integer = l.id;'],
        ),
        migrations.AlterField(
            model_name='talk',
            name='orig_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Language'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.RunSQL(
            sql=['UPDATE www_subtitle AS s SET language = l.id FROM www_language AS l WHERE s.language = l.lang_amara_short;', 'ALTER TABLE www_subtitle ALTER COLUMN language TYPE integer USING language::integer;'],
            reverse_sql=['ALTER TABLE www_subtitle ALTER COLUMN language TYPE character varying(15) USING language::character varying(15);', 'UPDATE www_subtitle AS s SET language = l.lang_amara_short FROM www_language AS l WHERE s.language::integer = l.id;'],
        ),
        migrations.RemoveField(
            model_name='language',
            name='amara_order',
        ),
        migrations.AddField(
            model_name='language',
            name='amara_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_short_2',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='language',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='orig_language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('language_en', models.CharField(default='', max_length=40)),
                ('language_de', models.CharField(blank=True, default='', max_length=40)),
                ('lang_amara_short', models.CharField(default='', max_length=15, unique=True)),
                ('lang_short_srt', models.CharField(blank=True, default='', max_length=15)),
                ('language_native', models.CharField(blank=True, default='', max_length=40)),
                ('amara_order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('lang_code_media', models.CharField(blank=True, default='', max_length=3)),
                ('lang_code_iso_639_1', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Language'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='is_original_lang',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='is_original_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='No title yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='days',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule_version',
            field=models.CharField(blank=True, default='0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeslot_duration',
            field=models.TimeField(blank=True, default='00:15'),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='day_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='day_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='amara_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Event_Days'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='duration',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Event'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_logo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_readable_pad',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_video_file',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_writable_pad',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='talk',
            name='orig_language',
            field=models.ForeignKey(blank=True, default=287, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Language'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='pad_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='talk',
            name='persons',
            field=models.ManyToManyField(blank=True, default=None, to='www.Speaker'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Rooms'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='subtitle_talk',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, default='ohne Titel', max_length=50),
        ),
        migrations.AlterField(
            model_name='talk',
            name='track',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Tracks'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='type_of',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Type_of'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_duration',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='youtube_key',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.States'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_syncing',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_transcribing',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_translating',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.TimeField(blank=True, default='11:00'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='duration',
            field=models.TimeField(blank=True, default='00:45'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_duration',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='day',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='www.Event_Days'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Event'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, default='ohne Titel', max_length=100),
        ),
        migrations.AlterField(
            model_name='talk',
            name='subtitle_talk',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='talk',
            name='subtitle_talk',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='talk',
            name='subtitle_talk',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
        migrations.RenameField(
            model_name='links',
            old_name='talk_link_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='talk_link_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='links',
            name='talk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Talk'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(blank=True, default='Link title', max_length=50),
        ),
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(blank=True, default='Link title', max_length=100),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(blank=True, default='Link title', max_length=200),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='state',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.States'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_video_file',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_video_file',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_video_file',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Rooms'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='track',
            field=models.ForeignKey(blank=True, default=40, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Tracks'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='type_of',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Type_of'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_automatic_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Event'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='type_of',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Type_of'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='building',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_syncing',
            field=models.TimeField(blank=True, default='00:00', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_transcribing',
            field=models.TimeField(blank=True, default='00:00', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_translating',
            field=models.TimeField(blank=True, default='00:00', verbose_name=''),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='time_quality_check_done',
            field=models.TimeField(blank=True, default='00:00', verbose_name=''),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_sync_to_ftp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_removal_from_ftp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Folders_Extensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('subfolder', models.CharField(blank=True, default='', max_length=10)),
                ('file_extension', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ftp_startfolder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='ftp_subfolders_extensions',
            field=models.ManyToManyField(blank=True, default=None, to='www.Folders_Extensions'),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='day_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='day_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, default='ohne Titel', max_length=150),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='tweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_removal_from_YT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_sync_to_YT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='youtube_key_t_1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='talk',
            name='youtube_key_t_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='tweet_autosync_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='last_changed_on_amara',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='talk',
            name='guid',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='talk',
            name='filename',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='subfolder_to_find_the_filenames',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='speaker',
            name='doppelgaenger_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Speaker'),
        ),
        migrations.AddField(
            model_name='talk',
            name='average_spm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='average_wpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='strokes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='time_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='recalculate_statistics',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Statistics_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('average_wpm', models.FloatField(blank=True, null=True)),
                ('average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Event')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics_Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('average_wpm', models.FloatField(blank=True, null=True)),
                ('average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Language')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics_Raw_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Speaker')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Talk')),
                ('recalculate_statistics', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics_raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Speaker')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Talk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Talk_Persons',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Speaker')),
                        ('talk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Talk')),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.AddField(
                    model_name='talk',
                    name='persons_new',
                    field=models.ManyToManyField(blank=True, default=None, through='www.Talk_Persons', to='www.Speaker'),
                ),
                migrations.RemoveField(
                    model_name='talk',
                    name='persons',
                ),
                migrations.RenameField(
                    model_name='talk',
                    old_name='persons_new',
                    new_name='persons',
                ),
            ],
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='touched',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='average_spm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='average_wpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='recalculate_statistics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='strokes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='time_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Talk_Persons',
            name='words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Statistics_Raw_Data',
        ),
        migrations.AddField(
            model_name='talk',
            name='recalculate_speakers_statistics',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='recalculate_statistics',
            new_name='recalculate_talk_statistics',
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers_strokes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers_time_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='Statistics_raw',
            new_name='Statistics_Raw_Data',
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers_average_spm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers_average_wpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics_event',
            name='n_most_frequent_words',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='statistics_speaker',
            name='n_most_frequent_words',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='talk',
            name='n_most_frequent_words',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='talk',
            name='n_most_frequent_words_speakers',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='talk_persons',
            name='n_most_frequent_words',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='abstract',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Speaker_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True)),
                ('speaker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='www.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_json_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_json_version',
            field=models.CharField(blank=True, default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='yt_caption_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='cdn_subtitles_root_folder',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='subfolder_in_sync_folder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_removal_from_sync_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_sync_to_sync_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='has_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='transcript_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Transcript'),
        ),
        migrations.AddField(
            model_name='talk',
            name='amara_activity_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='talk',
            name='amara_complete_update_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='talk',
            name='amara_update_interval',
            field=models.TimeField(blank=True, default='00:10'),
        ),
        migrations.AddField(
            model_name='talk',
            name='needs_complete_amara_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='next_amara_activity_check',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='frab_id_talk',
            field=models.CharField(blank=True, default='-1', max_length=10),
        ),
        migrations.RunSQL(
            sql=[],
            reverse_sql=['ALTER TABLE "www_talk" ALTER COLUMN "frab_id_talk" TYPE smallint USING "frab_id_talk"::smallint'],
        ),
        migrations.AddField(
            model_name='event',
            name='frab_id_prefix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='autotiming_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='frab_id',
            field=models.CharField(blank=True, default='-1', max_length=12),
        ),
        migrations.RunSQL(
            sql=[],
            reverse_sql=['ALTER TABLE "www_speaker" ALTER COLUMN "frab_id" TYPE smallint USING "frab_id"::smallint'],
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='is_original_lang',
            field=models.BooleanField(default=False, verbose_name='original language'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='frab_id_talk',
            field=models.CharField(blank=True, default='-1', max_length=12),
        ),
        migrations.RunSQL(
            sql=[],
            reverse_sql=['ALTER TABLE "www_talk" ALTER COLUMN "frab_id_talk" TYPE varchar(10) USING "frab_id_talk"::varchar(10)'],
        ),
        migrations.AlterField(
            model_name='type_of',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='frab_id',
            field=models.CharField(blank=True, default='-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='talk',
            name='frab_id_talk',
            field=models.CharField(blank=True, default='-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='speaker_links',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='talk',
            name='c3subtitles_youtube_key',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='talk',
            name='internal_comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.RemoveField(
            model_name='event',
            name='ftp_startfolder',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cdn_subtitles_root_folder',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ftp_subfolders_extensions',
        ),
        migrations.DeleteModel(
            name='Folders_Extensions',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='link_to_logo',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='link_to_readable_pad',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='pad_id',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='needs_removal_from_YT',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='needs_removal_from_ftp',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='needs_sync_to_YT',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='needs_sync_to_ftp',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='yt_caption_id',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='youtube_key_t_1',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='youtube_key_t_2',
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_code_media',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='event',
            name='kanboard_private_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='kanboard_public_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='kanboard_private_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='kanboard_public_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql=['ALTER TABLE www_event ADD CONSTRAINT www_event_kanboard_public_xor_private_project_id CHECK ((kanboard_public_project_id IS NULL) = (kanboard_private_project_id IS NULL))', 'ALTER TABLE www_subtitle ADD CONSTRAINT www_subtitle_kanboard_public_xor_private_task_id CHECK ((kanboard_public_task_id IS NULL) = (kanboard_private_task_id IS NULL))'],
            reverse_sql=['ALTER TABLE www_event DROP CONSTRAINT www_event_kanboard_public_xor_private_project_id', 'ALTER TABLE www_subtitle DROP CONSTRAINT www_subtitle_kanboard_public_xor_private_task_id'],
        ),
        migrations.AddField(
            model_name='talk',
            name='kanboard_private_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='kanboard_public_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule_xml_link',
            field=www.models.MaybeURLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_json_link',
            field=www.models.MaybeURLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='link_to_writable_pad',
            field=www.models.MaybeURLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='frab_id',
            field=models.CharField(blank=True, default='-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, default='ohne Titel', max_length=200),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='type_of',
            name='type',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='kanboard_private_task_id',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='kanboard_public_task_id',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='draft_needs_removal_from_sync_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='draft_needs_sync_to_sync_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='talk',
            name='youtube_key',
        ),
        migrations.AddField(
            model_name='talk',
            name='additional_amara_video_links',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='talk',
            name='primary_amara_video_link',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='trint_folder_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='talk',
            name='trint_transcript_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='blacklisted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeslot_duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 15)),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Language'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_syncing',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_transcribing',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_processed_translating',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='time_quality_check_done',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='blacklisted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='talk',
            name='day',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='www.Event_Days'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 45)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.PROTECT, to='www.Rooms'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.TimeField(blank=True, default=datetime.time(11, 0)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='frab_id_talk',
            field=models.CharField(blank=True, default='-1', max_length=100),
        ),
    ]
