# Generated by Django 2.2.17 on 2021-03-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0170_auto_20210123_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='blacklisted',
            new_name='unlisted',
        ),
        migrations.RenameField(
            model_name='subtitle',
            old_name='blacklisted',
            new_name='unlisted',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='blacklisted',
            new_name='unlisted',
        ),
    ]
