# Generated by Django 2.2.17 on 2021-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0171_auto_20210313_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='amara_update_interval',
            field=models.DurationField(blank=True, default='00:10'),
        ),
    ]
