# Generated by Django 2.2.17 on 2021-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0172_auto_20210402_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='amara_update_interval',
            field=models.DurationField(blank=True, default=600),
        ),
    ]
