# Generated by Django 2.2.17 on 2021-04-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0173_auto_20210402_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
