# Generated by Django 2.2.17 on 2021-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0176_auto_20210402_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
