# Generated by Django 2.2.17 on 2021-12-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0177_auto_20210402_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule_version',
            field=models.CharField(blank=True, default='0.0', max_length=250),
        ),
    ]
