# Generated by Django 2.2.17 on 2021-12-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0178_auto_20211226_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track',
            field=models.CharField(default='', max_length=100),
        ),
    ]
