# Generated by Django 3.2.10 on 2022-01-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0179_auto_20211226_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='notify_subtitle_needs_quality_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='notify_subtitle_needs_timing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='notify_subtitle_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='notify_transcript_available',
            field=models.BooleanField(default=False),
        ),
    ]
