# Generated by Django 3.2.10 on 2022-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0180_auto_20220108_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='notify_subtitle_needs_quality_control',
            new_name='notify_subtitle_ready_for_quality_control',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='needs_automatic_syncing',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='tweet_autosync_done',
        ),
        migrations.AlterField(
            model_name='talk',
            name='internal_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
