# Generated by Django 3.2.10 on 2022-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0181_auto_20220109_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='has_draft_subtitle_file',
            field=models.BooleanField(default=False),
        ),
    ]
