# Generated by Django 3.2.10 on 2023-09-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0182_subtitle_has_draft_subtitle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endings_to_remove_from_filenames',
            field=models.CharField(default='_hd.mp4;_sd.mp4;.mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='lang_subst_json',
            field=models.TextField(default="{'en':'eng', 'de':'deu'}"),
        ),
        migrations.AddField(
            model_name='event',
            name='webpages_to_find_video_links_and_filenames',
            field=models.TextField(default=''),
        ),
    ]
