# Generated by Django 3.2.10 on 2023-09-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0183_auto_20230917_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_all_webpages_urls_to_find_filenames_and_video_urls',
            field=models.BooleanField(default=False),
        ),
    ]
