# Generated by Django 3.2.10 on 2024-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0185_auto_20240118_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
