# Generated by Django 3.2.10 on 2024-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0186_alter_talk_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='c3subtitles_youtube_key',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='talk',
            name='filename',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
